input_select:
  <your_appliance_name>_state_machine:
    name: <Your Appliance Name> - State Machine
    options:
      - unplugged
      - powered
      - paused
      - job_ongoing
      - job_completed
    icon: mdi:<your_appliance_icon>
